### ISSUE TITLE
レートの計算式を変更する

### ISSUE THREAD

**Issue by EbiseLutica** [shrimpia/misskey-tools#26]
直近7日間の増加ノート数を集計し、データの数で割った値とする。

例：7日分のデータがあれば、それらを合計し、7で割る

これで直近1週間の、1日あたりのノート数がレートとなる。

**Comment by L1n4r1A** [comment]
メモ
1週間平均ベースにするのがやはりよさそうと言った感じ
ノート数だけじゃなくてリアクション数も取ってきて平均出せれば廃人度に加味できそうかも

**Comment by EbiseLutica** [comment]
最新7件分の増加ノート数を取ってきて、取った数で割るアルゴリズムにした

取得に失敗した場合は無効値扱いしないと、増加ノート数がでかすぎる問題がある #124
