### ISSUE TITLE
Calckey 対応

### ISSUE THREAD

**Issue by fu-sen** [shrimpia/misskey-tools#85]
Misskey v12 派生 Calckey の日本インスタンスが生まれています。 https://calckey.jp/
こちらから Misskey Tools へアカウント登録を試みたのですが、追加ができませんでした。
おそらく Calckey の名称になっているので、未知で判断できずにいると思われるのですが、
Misskey v12 ベースで対応が比較的容易に思われたのと、
今後日本でインスタンスが増える可能性があると思ったので、issues を入れてみました。
よろしくお願いいたします。

**Comment by EbiseLutica** [comment]
@fu-sen  私のCalckey アカウントでは追加できました……。不具合でしょうか。

登録時のエラーメッセージを教えていただけると助かります 🙏🏻 

<img width="153" alt="image" src="https://user-images.githubusercontent.com/7106976/222494995-a2bd783e-bae0-467e-a686-021e6b41b242.png">

**Comment by fu-sen** [comment]
ああ、正常だったようですね。Calckey.jp アカウントに通知を確認していて、
misskey.tools 側から操作したところ、アカウントの表示も確認できました。
何でしょうね？ calckey.jp は先日切り替えても表示されてなかったんです。
とりあえず現在は大丈夫そう、という事でこの issue 閉じます。不具合あったらまた issue 建てますので。
お手数かけました。ありがとうございました。
